run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  errcheck:
    check-blank: true
  
  govet:
    enable-all: true
  
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-dirs:
    - vendor
    - bin
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
